/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class AbstractRow {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AbstractRow(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AbstractRow obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        petuumJNI.delete_AbstractRow(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Init(int capacity) {
    petuumJNI.AbstractRow_Init(swigCPtr, this, capacity);
  }

  public AbstractRow Clone() {
    long cPtr = petuumJNI.AbstractRow_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new AbstractRow(cPtr, false);
  }

  public long get_update_size() {
    return petuumJNI.AbstractRow_get_update_size(swigCPtr, this);
  }

  public long SerializedSize() {
    return petuumJNI.AbstractRow_SerializedSize(swigCPtr, this);
  }

  public long Serialize(SWIGTYPE_p_void bytes) {
    return petuumJNI.AbstractRow_Serialize(swigCPtr, this, SWIGTYPE_p_void.getCPtr(bytes));
  }

  public boolean Deserialize(SWIGTYPE_p_void data, long num_bytes) {
    return petuumJNI.AbstractRow_Deserialize(swigCPtr, this, SWIGTYPE_p_void.getCPtr(data), num_bytes);
  }

  public void ApplyInc(int column_id, SWIGTYPE_p_void update) {
    petuumJNI.AbstractRow_ApplyInc(swigCPtr, this, column_id, SWIGTYPE_p_void.getCPtr(update));
  }

  public void ApplyBatchInc(SWIGTYPE_p_int column_ids, SWIGTYPE_p_void update_batch, int num_updates) {
    petuumJNI.AbstractRow_ApplyBatchInc(swigCPtr, this, SWIGTYPE_p_int.getCPtr(column_ids), SWIGTYPE_p_void.getCPtr(update_batch), num_updates);
  }

  public void ApplyIncUnsafe(int column_id, SWIGTYPE_p_void update) {
    petuumJNI.AbstractRow_ApplyIncUnsafe(swigCPtr, this, column_id, SWIGTYPE_p_void.getCPtr(update));
  }

  public void ApplyBatchIncUnsafe(SWIGTYPE_p_int column_ids, SWIGTYPE_p_void update_batch, int num_updates) {
    petuumJNI.AbstractRow_ApplyBatchIncUnsafe(swigCPtr, this, SWIGTYPE_p_int.getCPtr(column_ids), SWIGTYPE_p_void.getCPtr(update_batch), num_updates);
  }

  public void AddUpdates(int column_id, SWIGTYPE_p_void update1, SWIGTYPE_p_void update2) {
    petuumJNI.AbstractRow_AddUpdates(swigCPtr, this, column_id, SWIGTYPE_p_void.getCPtr(update1), SWIGTYPE_p_void.getCPtr(update2));
  }

  public void SubtractUpdates(int column_id, SWIGTYPE_p_void update1, SWIGTYPE_p_void update2) {
    petuumJNI.AbstractRow_SubtractUpdates(swigCPtr, this, column_id, SWIGTYPE_p_void.getCPtr(update1), SWIGTYPE_p_void.getCPtr(update2));
  }

  public void InitUpdate(int column_id, SWIGTYPE_p_void zero) {
    petuumJNI.AbstractRow_InitUpdate(swigCPtr, this, column_id, SWIGTYPE_p_void.getCPtr(zero));
  }

}
