/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class ClientTableConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ClientTableConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ClientTableConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        petuumJNI.delete_ClientTableConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTable_info(TableInfo value) {
    petuumJNI.ClientTableConfig_table_info_set(swigCPtr, this, TableInfo.getCPtr(value), value);
  }

  public TableInfo getTable_info() {
    long cPtr = petuumJNI.ClientTableConfig_table_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new TableInfo(cPtr, false);
  }

  public void setProcess_cache_capacity(int value) {
    petuumJNI.ClientTableConfig_process_cache_capacity_set(swigCPtr, this, value);
  }

  public int getProcess_cache_capacity() {
    return petuumJNI.ClientTableConfig_process_cache_capacity_get(swigCPtr, this);
  }

  public void setThread_cache_capacity(int value) {
    petuumJNI.ClientTableConfig_thread_cache_capacity_set(swigCPtr, this, value);
  }

  public int getThread_cache_capacity() {
    return petuumJNI.ClientTableConfig_thread_cache_capacity_get(swigCPtr, this);
  }

  public void setOplog_capacity(int value) {
    petuumJNI.ClientTableConfig_oplog_capacity_set(swigCPtr, this, value);
  }

  public int getOplog_capacity() {
    return petuumJNI.ClientTableConfig_oplog_capacity_get(swigCPtr, this);
  }

  public ClientTableConfig() {
    this(petuumJNI.new_ClientTableConfig(), true);
  }

}
