/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class petuum {
  public static void GetHostInfos(String server_file, MapInt32HostInfo host_map) {
    petuumJNI.GetHostInfos(server_file, MapInt32HostInfo.getCPtr(host_map), host_map);
  }

  public static void GetServerIDsFromHostMap(VectorInt32 server_ids, MapInt32HostInfo host_map) {
    petuumJNI.GetServerIDsFromHostMap(VectorInt32.getCPtr(server_ids), server_ids, MapInt32HostInfo.getCPtr(host_map), host_map);
  }

}
