/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class RowAccessor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected RowAccessor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RowAccessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        petuumJNI.delete_RowAccessor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RowAccessor() {
    this(petuumJNI.new_RowAccessor(), true);
  }

  public DenseIntRow GetDenseIntRow() {
    return new DenseIntRow(petuumJNI.RowAccessor_GetDenseIntRow(swigCPtr, this), false);
  }

  public DenseFloatRow GetDenseFloatRow() {
    return new DenseFloatRow(petuumJNI.RowAccessor_GetDenseFloatRow(swigCPtr, this), false);
  }

}
