/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class TableGroup {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TableGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TableGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        petuumJNI.delete_TableGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static int Init(TableGroupConfig table_group_config, boolean table_access) {
    return petuumJNI.TableGroup_Init(TableGroupConfig.getCPtr(table_group_config), table_group_config, table_access);
  }

  public static void ShutDown() {
    petuumJNI.TableGroup_ShutDown();
  }

  public static boolean CreateTable(int table_id, ClientTableConfig table_config) {
    return petuumJNI.TableGroup_CreateTable(table_id, ClientTableConfig.getCPtr(table_config), table_config);
  }

  public static void CreateTableDone() {
    petuumJNI.TableGroup_CreateTableDone();
  }

  public static void WaitThreadRegister() {
    petuumJNI.TableGroup_WaitThreadRegister();
  }

  public static int RegisterThread() {
    return petuumJNI.TableGroup_RegisterThread();
  }

  public static void DeregisterThread() {
    petuumJNI.TableGroup_DeregisterThread();
  }

  public static void Clock() {
    petuumJNI.TableGroup_Clock();
  }

  public static void GlobalBarrier() {
    petuumJNI.TableGroup_GlobalBarrier();
  }

  public static void RegisterDenseIntRow(int row_type) {
    petuumJNI.TableGroup_RegisterDenseIntRow(row_type);
  }

  public static void RegisterDenseFloatRow(int row_type) {
    petuumJNI.TableGroup_RegisterDenseFloatRow(row_type);
  }

  public static TableInt GetTableOrDieInt(int table_id) {
    return new TableInt(petuumJNI.TableGroup_GetTableOrDieInt(table_id), true);
  }

  public static TableFloat GetTableOrDieFloat(int table_id) {
    return new TableFloat(petuumJNI.TableGroup_GetTableOrDieFloat(table_id), true);
  }

  public TableGroup() {
    this(petuumJNI.new_TableGroup(), true);
  }

}
