/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class TableInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TableInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TableInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        petuumJNI.delete_TableInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTable_staleness(int value) {
    petuumJNI.TableInfo_table_staleness_set(swigCPtr, this, value);
  }

  public int getTable_staleness() {
    return petuumJNI.TableInfo_table_staleness_get(swigCPtr, this);
  }

  public void setRow_type(int value) {
    petuumJNI.TableInfo_row_type_set(swigCPtr, this, value);
  }

  public int getRow_type() {
    return petuumJNI.TableInfo_row_type_get(swigCPtr, this);
  }

  public void setRow_capacity(int value) {
    petuumJNI.TableInfo_row_capacity_set(swigCPtr, this, value);
  }

  public int getRow_capacity() {
    return petuumJNI.TableInfo_row_capacity_get(swigCPtr, this);
  }

  public TableInfo() {
    this(petuumJNI.new_TableInfo(), true);
  }

}
