/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class ThreadRowAccessor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ThreadRowAccessor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ThreadRowAccessor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        petuumJNI.delete_ThreadRowAccessor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ThreadRowAccessor() {
    this(petuumJNI.new_ThreadRowAccessor(), true);
  }

}
