/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class UpdateBatchInt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UpdateBatchInt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UpdateBatchInt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        petuumJNI.delete_UpdateBatchInt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UpdateBatchInt() {
    this(petuumJNI.new_UpdateBatchInt__SWIG_0(), true);
  }

  public UpdateBatchInt(UpdateBatchInt other) {
    this(petuumJNI.new_UpdateBatchInt__SWIG_1(UpdateBatchInt.getCPtr(other), other), true);
  }

  public void Update(int column_id, int update) {
    petuumJNI.UpdateBatchInt_Update(swigCPtr, this, column_id, update);
  }

  public VectorInt32 GetColIDs() {
    return new VectorInt32(petuumJNI.UpdateBatchInt_GetColIDs(swigCPtr, this), false);
  }

  public SWIGTYPE_p_int GetUpdates() {
    long cPtr = petuumJNI.UpdateBatchInt_GetUpdates(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public int GetBatchSize() {
    return petuumJNI.UpdateBatchInt_GetBatchSize(swigCPtr, this);
  }

}
