/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class UpdateBatchFloat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UpdateBatchFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UpdateBatchFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        petuumJNI.delete_UpdateBatchFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public UpdateBatchFloat() {
    this(petuumJNI.new_UpdateBatchFloat__SWIG_0(), true);
  }

  public UpdateBatchFloat(UpdateBatchFloat other) {
    this(petuumJNI.new_UpdateBatchFloat__SWIG_1(UpdateBatchFloat.getCPtr(other), other), true);
  }

  public void Update(int column_id, float update) {
    petuumJNI.UpdateBatchFloat_Update(swigCPtr, this, column_id, update);
  }

  public VectorInt32 GetColIDs() {
    return new VectorInt32(petuumJNI.UpdateBatchFloat_GetColIDs(swigCPtr, this), false);
  }

  public SWIGTYPE_p_float GetUpdates() {
    long cPtr = petuumJNI.UpdateBatchFloat_GetUpdates(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public int GetBatchSize() {
    return petuumJNI.UpdateBatchFloat_GetBatchSize(swigCPtr, this);
  }

}
