/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class VectorFloat {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorFloat(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorFloat obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        petuumJNI.delete_VectorFloat(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorFloat() {
    this(petuumJNI.new_VectorFloat__SWIG_0(), true);
  }

  public VectorFloat(long n) {
    this(petuumJNI.new_VectorFloat__SWIG_1(n), true);
  }

  public long size() {
    return petuumJNI.VectorFloat_size(swigCPtr, this);
  }

  public long capacity() {
    return petuumJNI.VectorFloat_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    petuumJNI.VectorFloat_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return petuumJNI.VectorFloat_isEmpty(swigCPtr, this);
  }

  public void clear() {
    petuumJNI.VectorFloat_clear(swigCPtr, this);
  }

  public void add(float x) {
    petuumJNI.VectorFloat_add(swigCPtr, this, x);
  }

  public float get(int i) {
    return petuumJNI.VectorFloat_get(swigCPtr, this, i);
  }

  public void set(int i, float val) {
    petuumJNI.VectorFloat_set(swigCPtr, this, i, val);
  }

}
