/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.petuum.petuum_ps;

public class VectorInt32 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected VectorInt32(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VectorInt32 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        petuumJNI.delete_VectorInt32(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public VectorInt32() {
    this(petuumJNI.new_VectorInt32__SWIG_0(), true);
  }

  public VectorInt32(long n) {
    this(petuumJNI.new_VectorInt32__SWIG_1(n), true);
  }

  public long size() {
    return petuumJNI.VectorInt32_size(swigCPtr, this);
  }

  public long capacity() {
    return petuumJNI.VectorInt32_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    petuumJNI.VectorInt32_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return petuumJNI.VectorInt32_isEmpty(swigCPtr, this);
  }

  public void clear() {
    petuumJNI.VectorInt32_clear(swigCPtr, this);
  }

  public void add(int x) {
    petuumJNI.VectorInt32_add(swigCPtr, this, x);
  }

  public int get(int i) {
    return petuumJNI.VectorInt32_get(swigCPtr, this, i);
  }

  public void set(int i, int val) {
    petuumJNI.VectorInt32_set(swigCPtr, this, i, val);
  }

}
