// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lda.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "lda.pb.hpp"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace stradslda {

namespace {

const ::google::protobuf::Descriptor* initinfo_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  initinfo_reflection_ = NULL;
const ::google::protobuf::Descriptor* singleint_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  singleint_reflection_ = NULL;
const ::google::protobuf::Descriptor* singlebucket_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  singlebucket_reflection_ = NULL;
const ::google::protobuf::Descriptor* topicrow_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  topicrow_reflection_ = NULL;
const ::google::protobuf::Descriptor* worker2coord_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  worker2coord_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_lda_2eproto() {
  protobuf_AddDesc_lda_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "lda.proto");
  GOOGLE_CHECK(file != NULL);
  initinfo_descriptor_ = file->message_type(0);
  static const int initinfo_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(initinfo, tokencnt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(initinfo, docnt_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(initinfo, wordmax_),
  };
  initinfo_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      initinfo_descriptor_,
      initinfo::default_instance_,
      initinfo_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(initinfo, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(initinfo, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(initinfo));
  singleint_descriptor_ = file->message_type(1);
  static const int singleint_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(singleint, ivalue_),
  };
  singleint_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      singleint_descriptor_,
      singleint::default_instance_,
      singleint_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(singleint, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(singleint, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(singleint));
  singlebucket_descriptor_ = file->message_type(2);
  static const int singlebucket_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(singlebucket, wid_),
  };
  singlebucket_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      singlebucket_descriptor_,
      singlebucket::default_instance_,
      singlebucket_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(singlebucket, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(singlebucket, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(singlebucket));
  topicrow_descriptor_ = file->message_type(3);
  static const int topicrow_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(topicrow, wordid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(topicrow, tid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(topicrow, assigned_),
  };
  topicrow_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      topicrow_descriptor_,
      topicrow::default_instance_,
      topicrow_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(topicrow, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(topicrow, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(topicrow));
  worker2coord_descriptor_ = file->message_type(4);
  static const int worker2coord_offsets_[12] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, ringsrc_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, ringdst_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, init_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, singlei_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, buckets_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, trow_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, summary_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, docll_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, moll1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, moll2_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, nzwt_),
  };
  worker2coord_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      worker2coord_descriptor_,
      worker2coord::default_instance_,
      worker2coord_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(worker2coord, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(worker2coord));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_lda_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    initinfo_descriptor_, &initinfo::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    singleint_descriptor_, &singleint::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    singlebucket_descriptor_, &singlebucket::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    topicrow_descriptor_, &topicrow::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    worker2coord_descriptor_, &worker2coord::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_lda_2eproto() {
  delete initinfo::default_instance_;
  delete initinfo_reflection_;
  delete singleint::default_instance_;
  delete singleint_reflection_;
  delete singlebucket::default_instance_;
  delete singlebucket_reflection_;
  delete topicrow::default_instance_;
  delete topicrow_reflection_;
  delete worker2coord::default_instance_;
  delete worker2coord_reflection_;
}

void protobuf_AddDesc_lda_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tlda.proto\022\tstradslda\"<\n\010initinfo\022\020\n\010to"
    "kencnt\030\001 \002(\005\022\r\n\005docnt\030\002 \002(\005\022\017\n\007wordmax\030\003"
    " \002(\005\"\033\n\tsingleint\022\016\n\006ivalue\030\001 \002(\005\"\037\n\014sin"
    "glebucket\022\017\n\003wid\030\001 \003(\005B\002\020\001\"A\n\010topicrow\022\016"
    "\n\006wordid\030\001 \001(\005\022\017\n\003tid\030\002 \003(\005B\002\020\001\022\024\n\010assig"
    "ned\030\003 \003(\005B\002\020\001\"\241\002\n\014worker2coord\022\014\n\004type\030\001"
    " \001(\005\022\017\n\007ringsrc\030\002 \001(\005\022\017\n\007ringdst\030\003 \001(\005\022!"
    "\n\004init\030\004 \003(\0132\023.stradslda.initinfo\022%\n\007sin"
    "glei\030\005 \003(\0132\024.stradslda.singleint\022(\n\007buck"
    "ets\030\006 \003(\0132\027.stradslda.singlebucket\022!\n\004tr"
    "ow\030\007 \003(\0132\023.stradslda.topicrow\022\017\n\007summary"
    "\030\010 \003(\005\022\r\n\005docll\030\t \001(\001\022\r\n\005moll1\030\n \001(\001\022\r\n\005"
    "moll2\030\013 \001(\001\022\014\n\004nzwt\030\014 \001(\005", 505);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "lda.proto", &protobuf_RegisterTypes);
  initinfo::default_instance_ = new initinfo();
  singleint::default_instance_ = new singleint();
  singlebucket::default_instance_ = new singlebucket();
  topicrow::default_instance_ = new topicrow();
  worker2coord::default_instance_ = new worker2coord();
  initinfo::default_instance_->InitAsDefaultInstance();
  singleint::default_instance_->InitAsDefaultInstance();
  singlebucket::default_instance_->InitAsDefaultInstance();
  topicrow::default_instance_->InitAsDefaultInstance();
  worker2coord::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_lda_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_lda_2eproto {
  StaticDescriptorInitializer_lda_2eproto() {
    protobuf_AddDesc_lda_2eproto();
  }
} static_descriptor_initializer_lda_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int initinfo::kTokencntFieldNumber;
const int initinfo::kDocntFieldNumber;
const int initinfo::kWordmaxFieldNumber;
#endif  // !_MSC_VER

initinfo::initinfo()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:stradslda.initinfo)
}

void initinfo::InitAsDefaultInstance() {
}

initinfo::initinfo(const initinfo& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:stradslda.initinfo)
}

void initinfo::SharedCtor() {
  _cached_size_ = 0;
  tokencnt_ = 0;
  docnt_ = 0;
  wordmax_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

initinfo::~initinfo() {
  // @@protoc_insertion_point(destructor:stradslda.initinfo)
  SharedDtor();
}

void initinfo::SharedDtor() {
  if (this != default_instance_) {
  }
}

void initinfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* initinfo::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return initinfo_descriptor_;
}

const initinfo& initinfo::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lda_2eproto();
  return *default_instance_;
}

initinfo* initinfo::default_instance_ = NULL;

initinfo* initinfo::New() const {
  return new initinfo;
}

void initinfo::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<initinfo*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  ZR_(tokencnt_, wordmax_);

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool initinfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:stradslda.initinfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 tokencnt = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &tokencnt_)));
          set_has_tokencnt();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_docnt;
        break;
      }

      // required int32 docnt = 2;
      case 2: {
        if (tag == 16) {
         parse_docnt:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &docnt_)));
          set_has_docnt();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_wordmax;
        break;
      }

      // required int32 wordmax = 3;
      case 3: {
        if (tag == 24) {
         parse_wordmax:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &wordmax_)));
          set_has_wordmax();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:stradslda.initinfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:stradslda.initinfo)
  return false;
#undef DO_
}

void initinfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:stradslda.initinfo)
  // required int32 tokencnt = 1;
  if (has_tokencnt()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->tokencnt(), output);
  }

  // required int32 docnt = 2;
  if (has_docnt()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->docnt(), output);
  }

  // required int32 wordmax = 3;
  if (has_wordmax()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->wordmax(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:stradslda.initinfo)
}

::google::protobuf::uint8* initinfo::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:stradslda.initinfo)
  // required int32 tokencnt = 1;
  if (has_tokencnt()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->tokencnt(), target);
  }

  // required int32 docnt = 2;
  if (has_docnt()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->docnt(), target);
  }

  // required int32 wordmax = 3;
  if (has_wordmax()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->wordmax(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:stradslda.initinfo)
  return target;
}

int initinfo::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 tokencnt = 1;
    if (has_tokencnt()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->tokencnt());
    }

    // required int32 docnt = 2;
    if (has_docnt()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->docnt());
    }

    // required int32 wordmax = 3;
    if (has_wordmax()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->wordmax());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void initinfo::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const initinfo* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const initinfo*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void initinfo::MergeFrom(const initinfo& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_tokencnt()) {
      set_tokencnt(from.tokencnt());
    }
    if (from.has_docnt()) {
      set_docnt(from.docnt());
    }
    if (from.has_wordmax()) {
      set_wordmax(from.wordmax());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void initinfo::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void initinfo::CopyFrom(const initinfo& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool initinfo::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  return true;
}

void initinfo::Swap(initinfo* other) {
  if (other != this) {
    std::swap(tokencnt_, other->tokencnt_);
    std::swap(docnt_, other->docnt_);
    std::swap(wordmax_, other->wordmax_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata initinfo::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = initinfo_descriptor_;
  metadata.reflection = initinfo_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int singleint::kIvalueFieldNumber;
#endif  // !_MSC_VER

singleint::singleint()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:stradslda.singleint)
}

void singleint::InitAsDefaultInstance() {
}

singleint::singleint(const singleint& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:stradslda.singleint)
}

void singleint::SharedCtor() {
  _cached_size_ = 0;
  ivalue_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

singleint::~singleint() {
  // @@protoc_insertion_point(destructor:stradslda.singleint)
  SharedDtor();
}

void singleint::SharedDtor() {
  if (this != default_instance_) {
  }
}

void singleint::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* singleint::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return singleint_descriptor_;
}

const singleint& singleint::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lda_2eproto();
  return *default_instance_;
}

singleint* singleint::default_instance_ = NULL;

singleint* singleint::New() const {
  return new singleint;
}

void singleint::Clear() {
  ivalue_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool singleint::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:stradslda.singleint)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 ivalue = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ivalue_)));
          set_has_ivalue();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:stradslda.singleint)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:stradslda.singleint)
  return false;
#undef DO_
}

void singleint::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:stradslda.singleint)
  // required int32 ivalue = 1;
  if (has_ivalue()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->ivalue(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:stradslda.singleint)
}

::google::protobuf::uint8* singleint::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:stradslda.singleint)
  // required int32 ivalue = 1;
  if (has_ivalue()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->ivalue(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:stradslda.singleint)
  return target;
}

int singleint::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 ivalue = 1;
    if (has_ivalue()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->ivalue());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void singleint::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const singleint* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const singleint*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void singleint::MergeFrom(const singleint& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_ivalue()) {
      set_ivalue(from.ivalue());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void singleint::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void singleint::CopyFrom(const singleint& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool singleint::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void singleint::Swap(singleint* other) {
  if (other != this) {
    std::swap(ivalue_, other->ivalue_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata singleint::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = singleint_descriptor_;
  metadata.reflection = singleint_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int singlebucket::kWidFieldNumber;
#endif  // !_MSC_VER

singlebucket::singlebucket()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:stradslda.singlebucket)
}

void singlebucket::InitAsDefaultInstance() {
}

singlebucket::singlebucket(const singlebucket& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:stradslda.singlebucket)
}

void singlebucket::SharedCtor() {
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

singlebucket::~singlebucket() {
  // @@protoc_insertion_point(destructor:stradslda.singlebucket)
  SharedDtor();
}

void singlebucket::SharedDtor() {
  if (this != default_instance_) {
  }
}

void singlebucket::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* singlebucket::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return singlebucket_descriptor_;
}

const singlebucket& singlebucket::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lda_2eproto();
  return *default_instance_;
}

singlebucket* singlebucket::default_instance_ = NULL;

singlebucket* singlebucket::New() const {
  return new singlebucket;
}

void singlebucket::Clear() {
  wid_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool singlebucket::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:stradslda.singlebucket)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 wid = 1 [packed = true];
      case 1: {
        if (tag == 10) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_wid())));
        } else if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 10, input, this->mutable_wid())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:stradslda.singlebucket)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:stradslda.singlebucket)
  return false;
#undef DO_
}

void singlebucket::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:stradslda.singlebucket)
  // repeated int32 wid = 1 [packed = true];
  if (this->wid_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_wid_cached_byte_size_);
  }
  for (int i = 0; i < this->wid_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->wid(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:stradslda.singlebucket)
}

::google::protobuf::uint8* singlebucket::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:stradslda.singlebucket)
  // repeated int32 wid = 1 [packed = true];
  if (this->wid_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _wid_cached_byte_size_, target);
  }
  for (int i = 0; i < this->wid_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->wid(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:stradslda.singlebucket)
  return target;
}

int singlebucket::ByteSize() const {
  int total_size = 0;

  // repeated int32 wid = 1 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->wid_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->wid(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _wid_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void singlebucket::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const singlebucket* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const singlebucket*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void singlebucket::MergeFrom(const singlebucket& from) {
  GOOGLE_CHECK_NE(&from, this);
  wid_.MergeFrom(from.wid_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void singlebucket::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void singlebucket::CopyFrom(const singlebucket& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool singlebucket::IsInitialized() const {

  return true;
}

void singlebucket::Swap(singlebucket* other) {
  if (other != this) {
    wid_.Swap(&other->wid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata singlebucket::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = singlebucket_descriptor_;
  metadata.reflection = singlebucket_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int topicrow::kWordidFieldNumber;
const int topicrow::kTidFieldNumber;
const int topicrow::kAssignedFieldNumber;
#endif  // !_MSC_VER

topicrow::topicrow()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:stradslda.topicrow)
}

void topicrow::InitAsDefaultInstance() {
}

topicrow::topicrow(const topicrow& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:stradslda.topicrow)
}

void topicrow::SharedCtor() {
  _cached_size_ = 0;
  wordid_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

topicrow::~topicrow() {
  // @@protoc_insertion_point(destructor:stradslda.topicrow)
  SharedDtor();
}

void topicrow::SharedDtor() {
  if (this != default_instance_) {
  }
}

void topicrow::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* topicrow::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return topicrow_descriptor_;
}

const topicrow& topicrow::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lda_2eproto();
  return *default_instance_;
}

topicrow* topicrow::default_instance_ = NULL;

topicrow* topicrow::New() const {
  return new topicrow;
}

void topicrow::Clear() {
  wordid_ = 0;
  tid_.Clear();
  assigned_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool topicrow::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:stradslda.topicrow)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 wordid = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &wordid_)));
          set_has_wordid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_tid;
        break;
      }

      // repeated int32 tid = 2 [packed = true];
      case 2: {
        if (tag == 18) {
         parse_tid:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_tid())));
        } else if (tag == 16) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 18, input, this->mutable_tid())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_assigned;
        break;
      }

      // repeated int32 assigned = 3 [packed = true];
      case 3: {
        if (tag == 26) {
         parse_assigned:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_assigned())));
        } else if (tag == 24) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26, input, this->mutable_assigned())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:stradslda.topicrow)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:stradslda.topicrow)
  return false;
#undef DO_
}

void topicrow::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:stradslda.topicrow)
  // optional int32 wordid = 1;
  if (has_wordid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->wordid(), output);
  }

  // repeated int32 tid = 2 [packed = true];
  if (this->tid_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_tid_cached_byte_size_);
  }
  for (int i = 0; i < this->tid_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->tid(i), output);
  }

  // repeated int32 assigned = 3 [packed = true];
  if (this->assigned_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_assigned_cached_byte_size_);
  }
  for (int i = 0; i < this->assigned_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->assigned(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:stradslda.topicrow)
}

::google::protobuf::uint8* topicrow::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:stradslda.topicrow)
  // optional int32 wordid = 1;
  if (has_wordid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->wordid(), target);
  }

  // repeated int32 tid = 2 [packed = true];
  if (this->tid_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _tid_cached_byte_size_, target);
  }
  for (int i = 0; i < this->tid_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->tid(i), target);
  }

  // repeated int32 assigned = 3 [packed = true];
  if (this->assigned_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
      _assigned_cached_byte_size_, target);
  }
  for (int i = 0; i < this->assigned_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->assigned(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:stradslda.topicrow)
  return target;
}

int topicrow::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 wordid = 1;
    if (has_wordid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->wordid());
    }

  }
  // repeated int32 tid = 2 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->tid_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->tid(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _tid_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated int32 assigned = 3 [packed = true];
  {
    int data_size = 0;
    for (int i = 0; i < this->assigned_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->assigned(i));
    }
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(data_size);
    }
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _assigned_cached_byte_size_ = data_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void topicrow::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const topicrow* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const topicrow*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void topicrow::MergeFrom(const topicrow& from) {
  GOOGLE_CHECK_NE(&from, this);
  tid_.MergeFrom(from.tid_);
  assigned_.MergeFrom(from.assigned_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_wordid()) {
      set_wordid(from.wordid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void topicrow::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void topicrow::CopyFrom(const topicrow& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool topicrow::IsInitialized() const {

  return true;
}

void topicrow::Swap(topicrow* other) {
  if (other != this) {
    std::swap(wordid_, other->wordid_);
    tid_.Swap(&other->tid_);
    assigned_.Swap(&other->assigned_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata topicrow::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = topicrow_descriptor_;
  metadata.reflection = topicrow_reflection_;
  return metadata;
}


// ===================================================================

#ifndef _MSC_VER
const int worker2coord::kTypeFieldNumber;
const int worker2coord::kRingsrcFieldNumber;
const int worker2coord::kRingdstFieldNumber;
const int worker2coord::kInitFieldNumber;
const int worker2coord::kSingleiFieldNumber;
const int worker2coord::kBucketsFieldNumber;
const int worker2coord::kTrowFieldNumber;
const int worker2coord::kSummaryFieldNumber;
const int worker2coord::kDocllFieldNumber;
const int worker2coord::kMoll1FieldNumber;
const int worker2coord::kMoll2FieldNumber;
const int worker2coord::kNzwtFieldNumber;
#endif  // !_MSC_VER

worker2coord::worker2coord()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:stradslda.worker2coord)
}

void worker2coord::InitAsDefaultInstance() {
}

worker2coord::worker2coord(const worker2coord& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:stradslda.worker2coord)
}

void worker2coord::SharedCtor() {
  _cached_size_ = 0;
  type_ = 0;
  ringsrc_ = 0;
  ringdst_ = 0;
  docll_ = 0;
  moll1_ = 0;
  moll2_ = 0;
  nzwt_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

worker2coord::~worker2coord() {
  // @@protoc_insertion_point(destructor:stradslda.worker2coord)
  SharedDtor();
}

void worker2coord::SharedDtor() {
  if (this != default_instance_) {
  }
}

void worker2coord::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* worker2coord::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return worker2coord_descriptor_;
}

const worker2coord& worker2coord::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_lda_2eproto();
  return *default_instance_;
}

worker2coord* worker2coord::default_instance_ = NULL;

worker2coord* worker2coord::New() const {
  return new worker2coord;
}

void worker2coord::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<worker2coord*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 7) {
    ZR_(type_, ringsrc_);
    ringdst_ = 0;
  }
  if (_has_bits_[8 / 32] & 3840) {
    ZR_(docll_, moll2_);
    nzwt_ = 0;
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  init_.Clear();
  singlei_.Clear();
  buckets_.Clear();
  trow_.Clear();
  summary_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool worker2coord::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:stradslda.worker2coord)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 type = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
          set_has_type();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_ringsrc;
        break;
      }

      // optional int32 ringsrc = 2;
      case 2: {
        if (tag == 16) {
         parse_ringsrc:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ringsrc_)));
          set_has_ringsrc();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_ringdst;
        break;
      }

      // optional int32 ringdst = 3;
      case 3: {
        if (tag == 24) {
         parse_ringdst:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ringdst_)));
          set_has_ringdst();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_init;
        break;
      }

      // repeated .stradslda.initinfo init = 4;
      case 4: {
        if (tag == 34) {
         parse_init:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_init()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_init;
        if (input->ExpectTag(42)) goto parse_singlei;
        break;
      }

      // repeated .stradslda.singleint singlei = 5;
      case 5: {
        if (tag == 42) {
         parse_singlei:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_singlei()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_singlei;
        if (input->ExpectTag(50)) goto parse_buckets;
        break;
      }

      // repeated .stradslda.singlebucket buckets = 6;
      case 6: {
        if (tag == 50) {
         parse_buckets:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_buckets()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_buckets;
        if (input->ExpectTag(58)) goto parse_trow;
        break;
      }

      // repeated .stradslda.topicrow trow = 7;
      case 7: {
        if (tag == 58) {
         parse_trow:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_trow()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_trow;
        if (input->ExpectTag(64)) goto parse_summary;
        break;
      }

      // repeated int32 summary = 8;
      case 8: {
        if (tag == 64) {
         parse_summary:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 64, input, this->mutable_summary())));
        } else if (tag == 66) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_summary())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_summary;
        if (input->ExpectTag(73)) goto parse_docll;
        break;
      }

      // optional double docll = 9;
      case 9: {
        if (tag == 73) {
         parse_docll:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &docll_)));
          set_has_docll();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(81)) goto parse_moll1;
        break;
      }

      // optional double moll1 = 10;
      case 10: {
        if (tag == 81) {
         parse_moll1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &moll1_)));
          set_has_moll1();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(89)) goto parse_moll2;
        break;
      }

      // optional double moll2 = 11;
      case 11: {
        if (tag == 89) {
         parse_moll2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &moll2_)));
          set_has_moll2();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(96)) goto parse_nzwt;
        break;
      }

      // optional int32 nzwt = 12;
      case 12: {
        if (tag == 96) {
         parse_nzwt:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &nzwt_)));
          set_has_nzwt();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:stradslda.worker2coord)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:stradslda.worker2coord)
  return false;
#undef DO_
}

void worker2coord::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:stradslda.worker2coord)
  // optional int32 type = 1;
  if (has_type()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  // optional int32 ringsrc = 2;
  if (has_ringsrc()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->ringsrc(), output);
  }

  // optional int32 ringdst = 3;
  if (has_ringdst()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->ringdst(), output);
  }

  // repeated .stradslda.initinfo init = 4;
  for (int i = 0; i < this->init_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->init(i), output);
  }

  // repeated .stradslda.singleint singlei = 5;
  for (int i = 0; i < this->singlei_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->singlei(i), output);
  }

  // repeated .stradslda.singlebucket buckets = 6;
  for (int i = 0; i < this->buckets_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->buckets(i), output);
  }

  // repeated .stradslda.topicrow trow = 7;
  for (int i = 0; i < this->trow_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      7, this->trow(i), output);
  }

  // repeated int32 summary = 8;
  for (int i = 0; i < this->summary_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      8, this->summary(i), output);
  }

  // optional double docll = 9;
  if (has_docll()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(9, this->docll(), output);
  }

  // optional double moll1 = 10;
  if (has_moll1()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(10, this->moll1(), output);
  }

  // optional double moll2 = 11;
  if (has_moll2()) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(11, this->moll2(), output);
  }

  // optional int32 nzwt = 12;
  if (has_nzwt()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(12, this->nzwt(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:stradslda.worker2coord)
}

::google::protobuf::uint8* worker2coord::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:stradslda.worker2coord)
  // optional int32 type = 1;
  if (has_type()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  // optional int32 ringsrc = 2;
  if (has_ringsrc()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->ringsrc(), target);
  }

  // optional int32 ringdst = 3;
  if (has_ringdst()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->ringdst(), target);
  }

  // repeated .stradslda.initinfo init = 4;
  for (int i = 0; i < this->init_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        4, this->init(i), target);
  }

  // repeated .stradslda.singleint singlei = 5;
  for (int i = 0; i < this->singlei_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        5, this->singlei(i), target);
  }

  // repeated .stradslda.singlebucket buckets = 6;
  for (int i = 0; i < this->buckets_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        6, this->buckets(i), target);
  }

  // repeated .stradslda.topicrow trow = 7;
  for (int i = 0; i < this->trow_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        7, this->trow(i), target);
  }

  // repeated int32 summary = 8;
  for (int i = 0; i < this->summary_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(8, this->summary(i), target);
  }

  // optional double docll = 9;
  if (has_docll()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(9, this->docll(), target);
  }

  // optional double moll1 = 10;
  if (has_moll1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(10, this->moll1(), target);
  }

  // optional double moll2 = 11;
  if (has_moll2()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(11, this->moll2(), target);
  }

  // optional int32 nzwt = 12;
  if (has_nzwt()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(12, this->nzwt(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:stradslda.worker2coord)
  return target;
}

int worker2coord::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional int32 type = 1;
    if (has_type()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->type());
    }

    // optional int32 ringsrc = 2;
    if (has_ringsrc()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->ringsrc());
    }

    // optional int32 ringdst = 3;
    if (has_ringdst()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->ringdst());
    }

  }
  if (_has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    // optional double docll = 9;
    if (has_docll()) {
      total_size += 1 + 8;
    }

    // optional double moll1 = 10;
    if (has_moll1()) {
      total_size += 1 + 8;
    }

    // optional double moll2 = 11;
    if (has_moll2()) {
      total_size += 1 + 8;
    }

    // optional int32 nzwt = 12;
    if (has_nzwt()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->nzwt());
    }

  }
  // repeated .stradslda.initinfo init = 4;
  total_size += 1 * this->init_size();
  for (int i = 0; i < this->init_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->init(i));
  }

  // repeated .stradslda.singleint singlei = 5;
  total_size += 1 * this->singlei_size();
  for (int i = 0; i < this->singlei_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->singlei(i));
  }

  // repeated .stradslda.singlebucket buckets = 6;
  total_size += 1 * this->buckets_size();
  for (int i = 0; i < this->buckets_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->buckets(i));
  }

  // repeated .stradslda.topicrow trow = 7;
  total_size += 1 * this->trow_size();
  for (int i = 0; i < this->trow_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->trow(i));
  }

  // repeated int32 summary = 8;
  {
    int data_size = 0;
    for (int i = 0; i < this->summary_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->summary(i));
    }
    total_size += 1 * this->summary_size() + data_size;
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void worker2coord::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const worker2coord* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const worker2coord*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void worker2coord::MergeFrom(const worker2coord& from) {
  GOOGLE_CHECK_NE(&from, this);
  init_.MergeFrom(from.init_);
  singlei_.MergeFrom(from.singlei_);
  buckets_.MergeFrom(from.buckets_);
  trow_.MergeFrom(from.trow_);
  summary_.MergeFrom(from.summary_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_type()) {
      set_type(from.type());
    }
    if (from.has_ringsrc()) {
      set_ringsrc(from.ringsrc());
    }
    if (from.has_ringdst()) {
      set_ringdst(from.ringdst());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_docll()) {
      set_docll(from.docll());
    }
    if (from.has_moll1()) {
      set_moll1(from.moll1());
    }
    if (from.has_moll2()) {
      set_moll2(from.moll2());
    }
    if (from.has_nzwt()) {
      set_nzwt(from.nzwt());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void worker2coord::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void worker2coord::CopyFrom(const worker2coord& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool worker2coord::IsInitialized() const {

  if (!::google::protobuf::internal::AllAreInitialized(this->init())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->singlei())) return false;
  return true;
}

void worker2coord::Swap(worker2coord* other) {
  if (other != this) {
    std::swap(type_, other->type_);
    std::swap(ringsrc_, other->ringsrc_);
    std::swap(ringdst_, other->ringdst_);
    init_.Swap(&other->init_);
    singlei_.Swap(&other->singlei_);
    buckets_.Swap(&other->buckets_);
    trow_.Swap(&other->trow_);
    summary_.Swap(&other->summary_);
    std::swap(docll_, other->docll_);
    std::swap(moll1_, other->moll1_);
    std::swap(moll2_, other->moll2_);
    std::swap(nzwt_, other->nzwt_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata worker2coord::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = worker2coord_descriptor_;
  metadata.reflection = worker2coord_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace stradslda

// @@protoc_insertion_point(global_scope)
